name: TriTown
main: net.trilleo.mc.plugins.tritown.Main
version: ${projectVersion}
api-version: 1.21
author: Trilleo
description: Custom Towny features for the Trilleo server
depend:
  - Towny
  - Vault

commands:
  tritown:
    description: Main command for the TriTown plugin
    usage: /tritown <subcommand> [args]
    aliases:
      - tt
